# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import pyqtsource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1572, 891)
        self.action_add_stdf_module = QAction(MainWindow)
        self.action_add_stdf_module.setObjectName(u"action_add_stdf_module")
        icon = QIcon()
        icon.addFile(u":/pyqt/source/images/Open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_add_stdf_module.setIcon(icon)
        self.action_cascade = QAction(MainWindow)
        self.action_cascade.setObjectName(u"action_cascade")
        icon1 = QIcon()
        icon1.addFile(u":/pyqt/source/images/lc_duplicatepage.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_cascade.setIcon(icon1)
        self.action_distribution = QAction(MainWindow)
        self.action_distribution.setObjectName(u"action_distribution")
        icon2 = QIcon()
        icon2.addFile(u":/pyqt/source/images/lc_drawchart.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_distribution.setIcon(icon2)
        self.action_distribution_trans = QAction(MainWindow)
        self.action_distribution_trans.setObjectName(u"action_distribution_trans")
        icon3 = QIcon()
        icon3.addFile(u":/pyqt/source/images/lc_aligndown.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_distribution_trans.setIcon(icon3)
        self.action_comparing = QAction(MainWindow)
        self.action_comparing.setObjectName(u"action_comparing")
        icon4 = QIcon()
        icon4.addFile(u":/pyqt/source/images/lc_designerdialog.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_comparing.setIcon(icon4)
        self.action_linear = QAction(MainWindow)
        self.action_linear.setObjectName(u"action_linear")
        icon5 = QIcon()
        icon5.addFile(u":/pyqt/source/images/lc_graphicfilterremovenoise.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_linear.setIcon(icon5)
        self.action_scatter = QAction(MainWindow)
        self.action_scatter.setObjectName(u"action_scatter")
        icon6 = QIcon()
        icon6.addFile(u":/pyqt/source/images/lc_linestyle.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_scatter.setIcon(icon6)
        self.action_box_plot = QAction(MainWindow)
        self.action_box_plot.setObjectName(u"action_box_plot")
        icon7 = QIcon()
        icon7.addFile(u":/pyqt/source/images/lc_distributeselection.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_box_plot.setIcon(icon7)
        self.action_mapping = QAction(MainWindow)
        self.action_mapping.setObjectName(u"action_mapping")
        icon8 = QIcon()
        icon8.addFile(u":/pyqt/source/images/lc_graphicfiltermosaic.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_mapping.setIcon(icon8)
        self.action_visual_map = QAction(MainWindow)
        self.action_visual_map.setObjectName(u"action_visual_map")
        icon9 = QIcon()
        icon9.addFile(u":/pyqt/source/images/lc_objectcatalog.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_visual_map.setIcon(icon9)
        self.action_merge = QAction(MainWindow)
        self.action_merge.setObjectName(u"action_merge")
        icon10 = QIcon()
        icon10.addFile(u":/pyqt/source/images/dbaddrelation.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_merge.setIcon(icon10)
        self.action_pyside2 = QAction(MainWindow)
        self.action_pyside2.setObjectName(u"action_pyside2")
        icon11 = QIcon()
        icon11.addFile(u":/pyqt/source/images/NavOverFlow_Info.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_pyside2.setIcon(icon11)
        self.action_tools = QAction(MainWindow)
        self.action_tools.setObjectName(u"action_tools")
        icon12 = QIcon()
        icon12.addFile(u":/pyqt/source/images/icon-set-squares-empty.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_tools.setIcon(icon12)
        self.action_email = QAction(MainWindow)
        self.action_email.setObjectName(u"action_email")
        icon13 = QIcon()
        icon13.addFile(u":/pyqt/source/images/lc_mailmergeemaildocuments.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_email.setIcon(icon13)
        self.action_qt_scatter = QAction(MainWindow)
        self.action_qt_scatter.setObjectName(u"action_qt_scatter")
        self.action_qt_scatter.setIcon(icon6)
        self.action_multiple_chart = QAction(MainWindow)
        self.action_multiple_chart.setObjectName(u"action_multiple_chart")
        icon14 = QIcon()
        icon14.addFile(u":/pyqt/source/images/lc_autooutline.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_multiple_chart.setIcon(icon14)
        self.action_path_select = QAction(MainWindow)
        self.action_path_select.setObjectName(u"action_path_select")
        icon15 = QIcon()
        icon15.addFile(u":/pyqt/source/images/lc_openremote.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_path_select.setIcon(icon15)
        self.action_processing_report = QAction(MainWindow)
        self.action_processing_report.setObjectName(u"action_processing_report")
        icon16 = QIcon()
        icon16.addFile(u":/pyqt/source/images/lc_dbviewtablenames.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_processing_report.setIcon(icon16)
        self.action_contact = QAction(MainWindow)
        self.action_contact.setObjectName(u"action_contact")
        icon17 = QIcon()
        icon17.addFile(u":/pyqt/source/images/lc_newwindow.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_contact.setIcon(icon17)
        self.action_web_search = QAction(MainWindow)
        self.action_web_search.setObjectName(u"action_web_search")
        icon18 = QIcon()
        icon18.addFile(u":/pyqt/source/images/hlinettp.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_web_search.setIcon(icon18)
        self.action_material_report = QAction(MainWindow)
        self.action_material_report.setObjectName(u"action_material_report")
        icon19 = QIcon()
        icon19.addFile(u":/pyqt/source/images/lc_presentationcurrentslide.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_material_report.setIcon(icon19)
        self.action_server_scan = QAction(MainWindow)
        self.action_server_scan.setObjectName(u"action_server_scan")
        icon20 = QIcon()
        icon20.addFile(u":/pyqt/source/images/lc_sbaexecutesql.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_server_scan.setIcon(icon20)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar_right = QToolBar(MainWindow)
        self.toolBar_right.setObjectName(u"toolBar_right")
        MainWindow.addToolBar(Qt.RightToolBarArea, self.toolBar_right)
        self.toolBar_up = QToolBar(MainWindow)
        self.toolBar_up.setObjectName(u"toolBar_up")
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.toolBar_up)

        self.toolBar_right.addAction(self.action_cascade)
        self.toolBar_right.addSeparator()
        self.toolBar_right.addAction(self.action_material_report)
        self.toolBar_right.addSeparator()
        self.toolBar_right.addAction(self.action_distribution)
        self.toolBar_right.addAction(self.action_distribution_trans)
        self.toolBar_right.addAction(self.action_comparing)
        self.toolBar_right.addAction(self.action_linear)
        self.toolBar_right.addAction(self.action_scatter)
        self.toolBar_right.addAction(self.action_box_plot)
        self.toolBar_right.addAction(self.action_mapping)
        self.toolBar_right.addAction(self.action_visual_map)
        self.toolBar_right.addAction(self.action_multiple_chart)
        self.toolBar_right.addSeparator()
        self.toolBar_right.addAction(self.action_contact)
        self.toolBar_right.addAction(self.action_merge)
        self.toolBar_right.addSeparator()
        self.toolBar_right.addAction(self.action_tools)
        self.toolBar_right.addSeparator()
        self.toolBar_right.addAction(self.action_pyside2)
        self.toolBar_right.addSeparator()
        self.toolBar_right.addAction(self.action_email)
        self.toolBar_right.addSeparator()
        self.toolBar_up.addAction(self.action_add_stdf_module)
        self.toolBar_up.addAction(self.action_path_select)
        self.toolBar_up.addSeparator()
        self.toolBar_up.addAction(self.action_web_search)
        self.toolBar_up.addSeparator()
        self.toolBar_up.addAction(self.action_server_scan)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_add_stdf_module.setText(QCoreApplication.translate("MainWindow", u"add_stdf_module", None))
#if QT_CONFIG(tooltip)
        self.action_add_stdf_module.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u6dfb\u52a0\u81ea\u9009STDF\u6570\u636e</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.action_cascade.setText(QCoreApplication.translate("MainWindow", u"cascade", None))
#if QT_CONFIG(tooltip)
        self.action_cascade.setToolTip(QCoreApplication.translate("MainWindow", u"\u7ea7\u8054\u663e\u793a\u5de5\u4f5c\u7a7a\u95f4\u4e2d\u7a97\u53e3", None))
#endif // QT_CONFIG(tooltip)
        self.action_distribution.setText(QCoreApplication.translate("MainWindow", u"distribution", None))
#if QT_CONFIG(tooltip)
        self.action_distribution.setToolTip(QCoreApplication.translate("MainWindow", u"\u6d4b\u8bd5\u6570\u636e\u5206\u5e03\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.action_distribution_trans.setText(QCoreApplication.translate("MainWindow", u"distribution_trans", None))
#if QT_CONFIG(tooltip)
        self.action_distribution_trans.setToolTip(QCoreApplication.translate("MainWindow", u"\u6a2a\u5411\u5206\u5e03\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.action_comparing.setText(QCoreApplication.translate("MainWindow", u"comparing", None))
#if QT_CONFIG(tooltip)
        self.action_comparing.setToolTip(QCoreApplication.translate("MainWindow", u"\u6bd4\u8f83\u5bc6\u5ea6\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.action_linear.setText(QCoreApplication.translate("MainWindow", u"linear", None))
#if QT_CONFIG(tooltip)
        self.action_linear.setToolTip(QCoreApplication.translate("MainWindow", u"\u7ebf\u6027\u56de\u5f52", None))
#endif // QT_CONFIG(tooltip)
        self.action_scatter.setText(QCoreApplication.translate("MainWindow", u"scatter", None))
#if QT_CONFIG(tooltip)
        self.action_scatter.setToolTip(QCoreApplication.translate("MainWindow", u"\u6563\u70b9\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.action_box_plot.setText(QCoreApplication.translate("MainWindow", u"box_plot", None))
#if QT_CONFIG(tooltip)
        self.action_box_plot.setToolTip(QCoreApplication.translate("MainWindow", u"\u7bb1\u7ebf\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.action_mapping.setText(QCoreApplication.translate("MainWindow", u"mapping", None))
#if QT_CONFIG(tooltip)
        self.action_mapping.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Soft&amp;Hard&amp;TESTNO Bin Mapping</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.action_visual_map.setText(QCoreApplication.translate("MainWindow", u"visual_map", None))
        self.action_merge.setText(QCoreApplication.translate("MainWindow", u"merge", None))
#if QT_CONFIG(tooltip)
        self.action_merge.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\u6570\u636e\u94fe\u63a5,\u7b97\u5b50\u53c2\u6570\u5236\u5b9a</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.action_pyside2.setText(QCoreApplication.translate("MainWindow", u"pyside2", None))
#if QT_CONFIG(tooltip)
        self.action_pyside2.setToolTip(QCoreApplication.translate("MainWindow", u"\u5173\u4e8ePYSIDE2", None))
#endif // QT_CONFIG(tooltip)
        self.action_tools.setText(QCoreApplication.translate("MainWindow", u"tools", None))
#if QT_CONFIG(tooltip)
        self.action_tools.setToolTip(QCoreApplication.translate("MainWindow", u"\u5de5\u5177", None))
#endif // QT_CONFIG(tooltip)
        self.action_email.setText(QCoreApplication.translate("MainWindow", u"email", None))
#if QT_CONFIG(tooltip)
        self.action_email.setToolTip(QCoreApplication.translate("MainWindow", u"\u53cd\u9988", None))
#endif // QT_CONFIG(tooltip)
        self.action_qt_scatter.setText(QCoreApplication.translate("MainWindow", u"qt_scatter", None))
#if QT_CONFIG(tooltip)
        self.action_qt_scatter.setToolTip(QCoreApplication.translate("MainWindow", u"qt\u6563\u70b9\u56fe,\u56e0\u6027\u80fd\u95ee\u9898,\u6570\u636e\u4f1a\u505a\u62bd\u6837", None))
#endif // QT_CONFIG(tooltip)
        self.action_multiple_chart.setText(QCoreApplication.translate("MainWindow", u"multiple_chart", None))
#if QT_CONFIG(tooltip)
        self.action_multiple_chart.setToolTip(QCoreApplication.translate("MainWindow", u"\u7ec4\u5408\u591a\u4e2aJMP\u811a\u672c\u540c\u65f6\u7ed8\u5236\u591a\u79cd\u56fe\u50cf", None))
#endif // QT_CONFIG(tooltip)
        self.action_path_select.setText(QCoreApplication.translate("MainWindow", u"path_select", None))
#if QT_CONFIG(tooltip)
        self.action_path_select.setToolTip(QCoreApplication.translate("MainWindow", u"\u4e00\u6b21\u5c06\u9009\u53d6\u6587\u4ef6\u5939\u4e0b\u7684STDF\u6570\u636e\u5bfc\u5165", None))
#endif // QT_CONFIG(tooltip)
        self.action_processing_report.setText(QCoreApplication.translate("MainWindow", u"\u5236\u7a0b\u80fd\u529b\u62a5\u544a", None))
        self.action_contact.setText(QCoreApplication.translate("MainWindow", u"\u6570\u7ec4\u7ec4\u5408\u5806\u53e0", None))
#if QT_CONFIG(tooltip)
        self.action_contact.setToolTip(QCoreApplication.translate("MainWindow", u"\u5373\u4e3a\u591a\u4efd\u6570\u636e\u4e0a\u4e0b\u7ec4\u5408\u4e3a\u4e00\u4efd", None))
#endif // QT_CONFIG(tooltip)
        self.action_web_search.setText(QCoreApplication.translate("MainWindow", u"\u670d\u52a1\u5668\u641c\u7d22", None))
        self.action_material_report.setText(QCoreApplication.translate("MainWindow", u"material_report", None))
#if QT_CONFIG(tooltip)
        self.action_material_report.setToolTip(QCoreApplication.translate("MainWindow", u"\u91cf\u4ea7\u6d4b\u8bd5\u6570\u636e\u62a5\u8868", None))
#endif // QT_CONFIG(tooltip)
        self.action_server_scan.setText(QCoreApplication.translate("MainWindow", u"server_scan", None))
#if QT_CONFIG(tooltip)
        self.action_server_scan.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Server Data Scan</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.toolBar_right.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar_3", None))
        self.toolBar_up.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar_4", None))
    # retranslateUi

